name: Vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk16@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: monitor
          args: --org=omsorgspenger --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git
